### ISSUE TITLE
Hero su slideshow

### ISSUE THREAD

**Issue by DeividasBa** [AlphaMod1/11-grupe-eShop#9]
Landingo pagrindinis page, su patiekalų slideshow.

**Comment by DeividasBa** [comment]
![73474984_555125578555783_8159016765095936000_n](https://user-images.githubusercontent.com/55393172/68652250-b5cf0080-0531-11ea-8b44-6d53acf40e32.jpg)

**Comment by zivile-b** [comment]
Reikia papildomai ideti (nav uzima 80px, kad nepalistu):
.hero {
    padding-top: 80px;
}
